package control;
// Generated 15/10/2018 22:12:06 by Hibernate Tools 4.3.1



/**
 * Par generated by hbm2java
 */
public class Par  implements java.io.Serializable {

    private Integer id;
    private String titulo;
    private String categoria;
    private int idA;
    private int idB;

    public String[] getPar(){
        return new String[]{
            String.valueOf(id),
            titulo,
            categoria,
            "audio/"+String.valueOf(idA)+".mp3 & audio/" + String.valueOf(idB)+".mp3",
            "img/"+String.valueOf(idA)+".png & img/" + String.valueOf(idB)+".png"
        };
    }
    
    public Par() {
    }

    public Par(String titulo, String categoria, int idA, int idB) {
       this.titulo = titulo;
       this.categoria = categoria;
       this.idA = idA;
       this.idB = idB;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public int getIdA() {
        return this.idA;
    }
    
    public void setIdA(int idA) {
        this.idA = idA;
    }
    public int getIdB() {
        return this.idB;
    }
    
    public void setIdB(int idB) {
        this.idB = idB;
    }




}


